# Setup
title:               "Computer Science/Security"
tagline:             'From Seungju Han'
description:         "Computer Science/Security"
url:                 http:/pezluna.github.io
baseurl:             ''
paginate:            1
permalink:           pretty

# About/contact
author:
  name:              Seungju Han
  email:             sjhan@jnu.ac.kr

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
